site_name: My Docs
site_url: https://docs.bnndesigns.com

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - redirects:
      redirect_maps:
        'divi/redirect-test.md': 'new-divi/sample-s2.md'

markdown_extensions:
  - attr_list