site_name: My Docs
site_url: https://docs.bnndesigns.com

nav:
  - Home: index.md
  - Divi:
      - Redirect Test: new-divi/redirect-test.md

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - redirects:
      redirect_maps:
        'divi/redirect-test.md': 'new-divi/redirect-test'

markdown_extensions:
  - attr_list