site_name: Testing Mkdocs Material
site_url: https://docs.bnndesigns.com

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.top

nav:
  - Home: index.md
  - Offsite: '!import https://github.com/Valastiri/submodule-testing?branch=main'
  - ...

plugins:
  - search
  - awesome-pages
  - multirepo:
      imported_repo: true
      url: https://github.com/Valastiri/submodule-testing
      section_name: Offsite
      dirs: ["mkdocs.yml", "docs/*"]
      yml_file: mkdocs.yml
      branch: main

markdown_extensions:
  - attr_list