site_name: Testing Mkdocs Material
site_url: https://docs.bnndesigns.com

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.top

plugins:
  - search

markdown_extensions:
  - attr_list