site_name: Testing Mkdocs Material
site_url: https://docs.bnndesigns.com

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.top

plugins:
  - search
  - awesome-pages
  - multirepo:
      cleanup: true
      repos:
        - section: Offsite
          import_url: 'https://github.com/Valastiri/submodule-testing?branch=main'
          edit_uri: /blob/main/

markdown_extensions:
  - attr_list