site_name: Testing Mkdocs Material
site_url: https://docs.bnndesigns.com/

theme:
  name: material
  pallete:
    scheme: slate
  favicon: /assets/BNN-favicon.png
  features:
    - navigation.tabs
    - navigation.topa

extra:
  version:
    provider: mike

plugins:
  - search
  - social
  - redirects:
      redirect_maps:
        'redirectme.md': 'section-1/test-r.md'

markdown_extensions:
  - attr_list