name: Build Check

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  set-review:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - name: Assign Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'Needs Review'
      - name: Verify Label # Ensures that label is appropriately set for following steps
        id: check-labels
        uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 1
          labels: "Needs Review"
          exit_type: success

  verify-labels:
    needs: set-review
    runs-on: ubuntu-latest
    if: needs.set-review.outputs.status == 'success'
    steps:
      - name: Auto Merge and Needs Review Logic
        if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') && contains(github.event.pull_request.labels.*.name, 'Needs Review') }}
        run: echo "RUN_REMOVE_LABEL=true" >> $GITHUB_ENV

      - name: Remove Label
        if: ${{ env.RUN_REMOVE_LABEL == 'true' }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Needs Review
        id: remove-label

      - name: Remove Label Failed
        if: ${{ steps.remove-label.outcome == 'failure' }}
        run: echo "Remove Label step failed" && exit 1

      - name: Remove Label Succeeded
        if: ${{ steps.remove-label.outcome == 'success' && steps.remove-label.outputs.code == '0' }}
        run: echo "Remove Label step succeeded and returned code 0"

      - name: Verify Label
        uses: mheap/github-action-required-labels@v4
        with:
          mode: exactly
          count: 0
          labels: "Needs Review"
          add_comment: true
          message: "This PR is being prevented from merging because it {{ provided }}. Maintainers can auto merge by applying the Auto Merge label."

  merge:
    needs: verify-labels
    if: ${{ success() && contains(github.event.pull_request.labels.*.name, 'Auto Merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 0
      - name: Make Build
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install -r requirements.txt
          mkdocs build -s
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Strict Build Failed! ❌ - Please checkout this PR locally to fix the issue before merging or see checks.',
            });
      - name: Auto merge pr
        if: ${{ success() }}
        run: gh pr merge --squash --auto --subject "${{ github.event.pull_request.title }}" "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  failed_validation:
    needs: merge
    if: ${{ failure() && contains(github.event.pull_request.labels.*.name, 'Auto Merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove Label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Auto Merge
      - name: Assign Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'Needs Review'