name: Build Validation

on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize, labeled, unlabeled]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'Needs Review') }}
    steps:
      - name: Assign Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'Needs Review'

  auto_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'Auto Merge') }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: Needs Review
        continue-on-error: true
        id: remove-label

      - name: Check Remove Label Exit Code
        if: ${{ steps.remove-label.outcome == 'success' && steps.remove-label.outputs.code == '0' }}
        run: echo "Remove Label step succeeded and returned code 0"

  review_required:
    runs-on: ubuntu-latest
    needs: auto_merge
    steps:
      - name: Prevent Merge
        if: ${{ contains(github.event.pull_request.labels.*.name, 'Needs Review') }}
        run: echo "::error::Pull request cannot be merged when Needs Review label is assigned." && exit 1

  validate:
    needs: auto_merge
    if: ${{ success () && contains(github.event.pull_request.labels.*.name, 'Auto Merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR SHA
        id: sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 0
      - name: Make Build
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          pip install -r requirements.txt
          mkdocs build -s
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Strict Build Failed! ❌',
            });
      - name: Auto merge pr
        if: ${{ success() }}
        run: gh pr merge --squash --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
