name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Verify Changelog"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip
    - name: Comment on PR
      uses: actions/github-script@v3
      id: pr
      with:
        script: |
          var fs = require('fs');
          var issue_number = Number(fs.readFileSync('./NR'));
        github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Find Comment
        if: success () || failure ()
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ steps.pr.outputs.issue_number == '' }}
          comment-author: 'github-actions[bot]'
          body-includes: Please add changelog entry. ❌
      - name: Create comment
        if: ${{ steps.fc.outputs.comment-id == '' && failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please add changelog entry. ❌
      - name: Update comment
        if: ${{ steps.fc.outputs.comment-id != '' && success() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Thank you. Changelog Verified!
          reactions: rocket
          edit-mode: replace