name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Verify Changelog"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        if: success () || failure ()
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Please add changelog entry. ❌
      - name: Create comment
        if: ${{ steps.fc.outputs.comment-id == '' && failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please add changelog entry. ❌
      - name: Update comment
        if: ${{ steps.fc.outputs.comment-id != '' && success() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            Thank you. Changelog Verified!
          reactions: rocket
          edit-mode: replace