name: deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Primary
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Dependencies and mkdocs build
        run: |
          pip install -r requirements.txt
          mkdocs build

      - name: Github ENV
        if: github.ref == 'refs/heads/master'
        run: |
          echo "MKDOCS_VERSION=$(mkdocs --version | cut -d " " -f 3)" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV

      - name: Deploy updated build
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          destination_dir: ./
          keep_files: true
          allow_empty_commit: true
          full_commit_message: Deployed ${{ env.SHORT_SHA }} with MkDocs ${{ env.MKDOCS_VERSION }}

      - name: fetch gh-pages
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create Dev versioning
        run: mike deploy --push 0.9.0

