# This is a basic workflow to help you get started with Actions

name: PR Reviewed
on:
  issue_comment:
    types: [created, edited]
      
jobs:
  ondemand: 
    runs-on: ubuntu-latest
    if: github.event.comment.body == "Ok to test"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build Mkdocs
        run: pip install mkdocs-material
      - run: mkdocs build --clean --no-directory-urls
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: Site Demo
          path: /home/runner/work/test-mk/test-mk/site
          
