name: Verify Changelog

on:
  pull_request_target:
    types: [opened, ready_for_review, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: verify-changelog
        uses: tj-actions/changed-files@v23.1
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - name: Succesful check of changes to CHANGELOG.md
        if: contains(steps.verify-changelog.outputs.modified_files, 'CHANGELOG.md')
        run: |
          echo "Changelog Verified"
      - name: Run if CHANGELOG.md has not been updated
        if: steps.verify-changelog.outputs.any_changed != 'true'
        run: |
          echo "No Changes found. Please add changelog entry."
          exit 1
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please add changelog entry. ❌',
            });